name: Exemple cicd
on:
  push:
    branches: [main]

jobs:
  job1:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:
      - name: step 1
        run: echo "This works great"
      # 1. Récupération du code source
      - name: Checkout code
        uses: actions/checkout@v7
      # 2. Configuration de Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install bandit
      # 4. Étape 1 : Analyse statique (SAST) avec Bandit
      # -r : récursif, -ll : niveau de sévérité/confiance minimum, --format json (optionnel)
      - name: Run Bandit SAST Scan
        run: |
          echo "Lancement de l'analyse Bandit..."
          bandit -r . -f json -o bandit-report.json || true
          bandit -r .
      - name: Set Environment Variables
        run: |
          echo "DATABASE_URL=postgresql://test_user:test_password@localhost:5432/test_db" >> $GITHUB_ENV
      - name: Run Alembic Migrations
        run: |
          alembic upgrade head

      # 2. Lancement temporaire de l'API FastAPI avec Uvicorn en arrière-plan
      - name: 2. Start FastAPI Application
        run: |
          uvicorn main:app --host 0.0.0.0 --port 8000 &
          # Attendre quelques secondes que l'API démarre complètement
          sleep 4

      # 3. Scan dynamique de l'API avec OWASP ZAP (DAST) via Docker
      - name: 3. DAST Scan with OWASP ZAP
        run: |
          docker run --rm --network host -t owasp/zap2docker-stable zap-baseline.py \
            -t http://127.0.0.1:8000/ \
            -r zap_report.html || true
      - name: Upload Security Reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            bandit-report.json
            zap_report.html